# Mod info
mod_id=regrowth
mod_name=Regrowth
mod_version=61.34.3
mod_group=com.mactso.regrowth
mod_license=MIT
mod_authors=MacTso, Lupicus
mod_description=Adds various monster and villager actions that happen periodically.
archive_name=Regrowth-Forge-CC

# Minecraft & Forge versions
minecraft_version=1.21.11
mc_version=1.21.11
forge_version=61.0.3
mappings_channel=official
mappings_version=1.21.11

# JVM args for Gradle tasks
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false