# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.9
loader_version=0.18.0
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=134.34.6
maven_group=com.mactso.regrowth
archives_base_name=fabric-regrowth-CC-1.21.9

# Dependencies
fabric_version=0.134.0+1.21.9