# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=regrowth
mod_group=com.mactso.regrowth
mod_version=59.34.6
mod_license=MIT
mod_authors=MacTso, Lupicus
mod_description=Adds various monster and villager actions that happen periodically.
archive_name=Forge-Regrowth-CC

# Minecraft & Forge versions
mc_version=1.21.9
forge_version=59.0.5
mappings_channel=official
mappings_version=1.21.9

# JVM args for Gradle tasks
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false